const tokenSelect = document.querySelector('#role');
const content = document.querySelector('#content');
const modal = document.querySelector('#modal');
const modalContent = document.querySelector('#modal-content');
let view = 'overview';
const titles = {overview:'Overview',orders:'Client Service Orders',programs:'Program Register',assignments:'Escort Assignment',duty:'Vessel Duty',reviews:'Confirmation & Review Queue','release-slips':'Release Slips','ghat-duty':'Ghat Duty Review',completion:'Program Completion',settlements:'Settlement Review',identity:'Employee Identity',vessels:'Vessel Directory',clients:'Client Directory',audit:'Audit & Message History',reports:'Reports',settings:'Settings'};
const esc = (x) => String(x ?? '—').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path, options={}) {
  const isForm = options.body instanceof FormData;
  const headers={'Authorization':`Bearer ${tokenSelect.value}`,...options.headers};
  if(!isForm) headers['Content-Type']='application/json';
  const response = await fetch(`/api${path}`, { ...options, headers });
  const data = await response.json().catch(()=>({detail:response.statusText}));
  if (!response.ok) throw new Error(data.detail || `Request failed (${response.status})`);
  return data;
}
function table(headers, rows) { return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h[0]}</th>`).join('')}</tr></thead><tbody>${rows.length ? rows.map(row=>`<tr>${headers.map(h=>`<td>${h[1](row)}</td>`).join('')}</tr>`).join('') : `<tr><td colspan="${headers.length}" class="empty">No records yet</td></tr>`}</tbody></table></div>`; }
function pill(value){return `<span class="pill ${esc(value)}">${esc(value)}</span>`}
function evidence(value){return value&&value!=='—'?`<button class="evidence-link secondary" data-evidence="${esc(value)}">${esc(value)}</button>`:'—'}
function panel(title, body, action=''){return `<section class="panel"><div class="panel-head"><h2>${title}</h2>${action}</div>${body}</section>`}
function openForm(title, fields, submitLabel, submit) {
  modalContent.innerHTML = `<h2>${title}</h2><form id="entry-form" class="form-grid">${fields.map(f=>`<div class="field ${f.full?'full':''}"><label>${f.label}</label>${f.area?`<textarea name="${f.name}" ${f.required?'required':''} placeholder="${f.placeholder||''}"></textarea>`:`<input name="${f.name}" type="${f.type||'text'}" ${f.type==='file'?'accept="image/jpeg,image/png,image/webp,application/pdf"':''} ${f.required?'required':''} ${f.value && f.type!=='file'?`value="${f.value}"`:''} ${f.placeholder?`placeholder="${f.placeholder}"`:''}>`}</div>`).join('')}<div class="form-actions"><button type="button" class="secondary" onclick="modal.close()">Cancel</button><button>${submitLabel}</button></div></form>`;
  modal.showModal();
  document.querySelector('#entry-form').addEventListener('submit', async e=>{e.preventDefault(); const fd=new FormData(e.currentTarget);const data=Object.fromEntries(fd);try{await submit(data,fd);modal.close();toast('Saved. Evidence and audit event recorded.');render()}catch(err){toast(err.message)}});
}
function toast(message){const el=document.createElement('div');el.className='toast';el.textContent=message;document.body.append(el);setTimeout(()=>el.remove(),3600)}
const field=(name,label,extra={})=>({name,label,...extra});
async function render(){
 document.querySelector('#title').textContent=titles[view]; content.innerHTML='<div class="panel">Loading…</div>';
 try {
  if(view==='overview'){
   const d=await api('/overview'), programs=await api('/programs'), reviews=await api('/reviews');
   content.innerHTML=`<div class="alert">Standalone synthetic mode. No production connections, payroll posting, or WhatsApp listener are enabled.</div><div class="stats">${[['Service Orders',d.orders],['Programs',d.programs],['Open Reviews',d.reviews],['Ghat Duty Reviews',d.ghat_reviews]].map(x=>`<article class="card"><small>${x[0]}</small><strong>${x[1]}</strong></article>`).join('')}</div><div class="layout-two">${panel('Active Program Register',table([['Lighter',r=>esc(r.lighter_vessel)],['Escort Mobile',r=>esc(r.escort_mobile)],['Duty Start',r=>esc(r.duty_start_date)],['Status',r=>pill(r.status)]],programs.slice(0,5)))}${panel('Needs Review',table([['Type',r=>esc(r.kind)],['Summary',r=>esc(r.summary)],['Status',r=>pill(r.status)]],reviews.filter(r=>r.status==='pending').slice(0,5)))}</div>`;
  } else if(view==='orders'){
   const rows=await api('/orders'); content.innerHTML=panel('Orders and Drafts',table([['Status',r=>pill(r.status)],['Mother Vessel',r=>esc(r.mother_vessel)],['Lighter Vessel',r=>esc(r.lighter_vessel)],['Master Mobile',r=>esc(r.master_mobile)],['Message Date',r=>esc(r.message_date)],['Duty Start',r=>esc(r.duty_start_date)],['Shift',r=>esc(r.shift)],['Original Order',r=>evidence(r.source_evidence_id)],['Action',r=>r.status==='draft'?`<div class="actions"><button class="confirm" data-id="${r.id}">Confirm</button><button class="clarify secondary" data-id="${r.id}">Clarify</button></div>`:'—']],rows),'<button id="new-order">+ Service Order</button>');
   document.querySelector('#new-order').onclick=()=>openForm('Create Service Order',[field('source_ref','Synthetic source message reference',{required:true,value:`demo-order-${Date.now()}`}),field('client_id','Client ID',{value:'client-demo'}),field('message_date','Message Date (ISO)',{value:new Date().toISOString().slice(0,10)}),field('raw_text','Original message / extracted fields',{area:true,full:true,placeholder:'Mother Vessel: MV SAMPLE\nLighter Vessel: SAMPLE LIGHTER\nMaster Mobile: 01612345678'})],'Save Draft',d=>api('/orders',{method:'POST',body:JSON.stringify(d)}));
   document.querySelectorAll('.confirm').forEach(b=>b.onclick=()=>openForm('Admin Confirmation',[field('source_ref','Confirmation evidence reference',{required:true,value:`demo-confirm-${Date.now()}`}),field('escort_name','Escort Name',{required:true}),field('escort_mobile','Escort Mobile',{required:true}),field('duty_start_date','Duty Start Date',{required:true,type:'date'}),field('shift','Shift D/N',{required:true}),field('mother_vessel','Mother Vessel',{required:true}),field('lighter_vessel','Lighter Vessel',{required:true}),field('master_mobile','Master Mobile'),field('message_date','Message Date (ISO)',{value:new Date().toISOString().slice(0,10)})],'Confirm Program',d=>api(`/orders/${b.dataset.id}/confirm`,{method:'POST',body:JSON.stringify(d)})));
   document.querySelectorAll('.clarify').forEach(b=>b.onclick=()=>openForm('Link Clarification to Existing Order',[field('source_ref','Synthetic clarification evidence reference',{required:true,value:`demo-clarification-${Date.now()}`}),field('raw_text','Clarification message text',{required:true,area:true,full:true})],'Link Message',d=>api(`/orders/${b.dataset.id}/messages`,{method:'POST',body:JSON.stringify(d)})));
  } else if(view==='programs'){
   const rows=await api('/programs');content.innerHTML=panel('Confirmed Programs and Duty',table([['Mother Vessel',r=>esc(r.mother_vessel)],['Lighter Vessel',r=>esc(r.lighter_vessel)],['Escort',r=>esc(r.escort_name)],['Mobile',r=>esc(r.escort_mobile)],['Start',r=>esc(r.duty_start_date)],['Shift',r=>esc(r.shift)],['Status',r=>pill(r.status)],['Actions',r=>r.status==='confirmed'?`<div class="actions"><button class="start" data-id="${r.id}">Start Duty</button><button class="replace secondary" data-id="${r.id}">Replacement Review</button></div>`:r.status==='released'?`<button class="complete" data-id="${r.id}">Completion Review</button>`:`<div class="actions"><button class="slip secondary" data-id="${r.id}">Release Slip</button><button class="settle secondary" data-id="${r.id}">Settlement</button><button class="correct secondary" data-id="${r.id}">Correction</button><button class="cancel warn" data-id="${r.id}">Cancel Review</button><button class="replace secondary" data-id="${r.id}">Replacement Review</button></div>`]],rows));
   document.querySelectorAll('.start').forEach(b=>b.onclick=async()=>{const evidence_ref=prompt('Synthetic attendance/movement evidence reference:');if(!evidence_ref)return;const occurred_at=prompt('Observed duty date/time (ISO):',`${new Date().toISOString().slice(0,10)}T00:00:00Z`);if(!occurred_at)return;try{const r=await api(`/programs/${b.dataset.id}/duty-start`,{method:'POST',body:JSON.stringify({evidence_ref,occurred_at,evidence_type:'attendance_or_movement'})});toast(`Duty start awaits admin verification (${r.review_id})`);render()}catch(e){toast(e.message)}});
   document.querySelectorAll('.complete').forEach(b=>b.onclick=async()=>{const evidence_id=prompt('Verified completion evidence reference:');if(!evidence_id)return;try{await api(`/programs/${b.dataset.id}/completion-review`,{method:'POST',body:JSON.stringify({evidence_id})});toast('Completion review created; program is not yet completed');render()}catch(e){toast(e.message)}});
   document.querySelectorAll('.correct').forEach(b=>b.onclick=async()=>{const evidence_id=prompt('Correction evidence reference:');if(!evidence_id)return;try{await api(`/programs/${b.dataset.id}/correction-review`,{method:'POST',body:JSON.stringify({evidence_id})});toast('Correction review created; program unchanged');render()}catch(e){toast(e.message)}});
   document.querySelectorAll('.cancel').forEach(b=>b.onclick=async()=>{const evidence_id=prompt('Authoritative cancellation evidence reference:');if(!evidence_id)return;try{await api(`/programs/${b.dataset.id}/cancel-review`,{method:'POST',body:JSON.stringify({evidence_id})});toast('Cancellation review created; program unchanged');render()}catch(e){toast(e.message)}});
   document.querySelectorAll('.replace').forEach(b=>b.onclick=async()=>{const evidence_id=prompt('Replacement/next assignment evidence reference:');if(!evidence_id)return;try{await api(`/programs/${b.dataset.id}/replacement-review`,{method:'POST',body:JSON.stringify({evidence_id})});toast('Replacement review created; current assignment unchanged');render()}catch(e){toast(e.message)}});
   document.querySelectorAll('.slip').forEach(b=>b.onclick=()=>openForm('Upload/Record Release Slip (synthetic only)',[field('file','Synthetic slip image or PDF',{type:'file',full:true}),field('source_ref','Or media evidence reference',{value:`demo-slip-${Date.now()}`}),field('release_date','Release Date',{type:'date'}),field('shift','Shift'),field('total_duty','Total Duty (evidence only)'),field('salary','Salary shown (unverified)'),field('conveyance','Conveyance shown'),field('location','Release Location'),field('confidence','OCR confidence 0-1',{type:'number',value:'0.6'}),field('ocr_text','OCR/manual text',{area:true,full:true})],'Submit for Verification',(d,fd)=>{const file=fd.get('file');if(file&&file.size)return api(`/programs/${b.dataset.id}/release-upload`,{method:'POST',body:(()=>{const form=new FormData();form.append('file',file);return form})()});return api(`/programs/${b.dataset.id}/release-slips`,{method:'POST',body:JSON.stringify(d)})}));
   document.querySelectorAll('.settle').forEach(b=>b.onclick=()=>openForm('Synthetic Settlement Review',[field('duty_days','Verified duty days',{type:'number'}),field('daily_rate','Daily rate (required; no default)',{type:'number'}),field('deductions','Synthetic deductions',{type:'number',value:'0'})],'Calculate Review Preview',d=>api(`/programs/${b.dataset.id}/settlement`,{method:'POST',body:JSON.stringify(Object.fromEntries(Object.entries(d).map(([k,v])=>[k,v===''?null:Number(v)])))})));
  } else if(view==='assignments'){
   const rows=await api('/assignments');content.innerHTML=panel('Assignment History',table([['Escort',r=>esc(r.escort_name)],['Operational Mobile',r=>esc(r.employee_id)],['Mother Vessel',r=>esc(r.mother_vessel)],['Lighter',r=>esc(r.lighter_vessel)],['Start',r=>esc(r.start_date)],['Shift',r=>esc(r.shift)],['End evidence',r=>esc(r.end_date)],['Status',r=>pill(r.status)],['Program',r=>pill(r.program_status)]],rows));
  } else if(view==='duty'){
   const rows=(await api('/programs')).filter(r=>['confirmed','running'].includes(r.status)), evidence=await api('/duty-evidence');content.innerHTML=panel('Confirmed and Active Vessel Duty',table([['Mother Vessel',r=>esc(r.mother_vessel)],['Lighter',r=>esc(r.lighter_vessel)],['Escort',r=>esc(r.escort_name)],['Mobile',r=>esc(r.escort_mobile)],['Start Date',r=>esc(r.duty_start_date)],['Shift',r=>esc(r.shift)],['Operational Status',r=>pill(r.status)]],rows))+panel('Attendance and Movement Evidence',table([['Mother Vessel',r=>esc(r.mother_vessel)],['Lighter',r=>esc(r.lighter_vessel)],['Escort Mobile',r=>esc(r.escort_mobile)],['Evidence Type',r=>esc(r.evidence_type)],['Observed',r=>esc(r.occurred_at)],['Verification',r=>pill(r.verification_status)],['Source',r=>evidence(r.evidence_id)]],evidence));
  } else if(view==='completion'){
   const rows=(await api('/programs')).filter(r=>['released','completed'].includes(r.status));content.innerHTML=panel('Release and Completion States',`<p class="note">Release is not completion. Completion requires a separate evidence-backed Admin review.</p>`+table([['Mother Vessel',r=>esc(r.mother_vessel)],['Lighter',r=>esc(r.lighter_vessel)],['Escort Mobile',r=>esc(r.escort_mobile)],['Duty Start',r=>esc(r.duty_start_date)],['Release Date',r=>esc(r.release_date)],['Completion Date',r=>esc(r.completion_date)],['Status',r=>pill(r.status)],['Action',r=>r.status==='released'?`<button class="complete" data-id="${r.id}">Request Completion Review</button>`:'—']],rows));
   document.querySelectorAll('.complete').forEach(b=>b.onclick=async()=>{const evidence_id=prompt('Synthetic completion evidence reference:');if(!evidence_id)return;try{await api(`/programs/${b.dataset.id}/completion-review`,{method:'POST',body:JSON.stringify({evidence_id})});toast('Completion review created');render()}catch(e){toast(e.message)}});
  } else if(view==='vessels'){
   const rows=await api('/vessels');content.innerHTML=panel('Synthetic Vessel Directory',table([['Name',r=>esc(r.name)],['Type',r=>pill(r.vessel_type)],['Synthetic',r=>r.synthetic?'Yes':'No']],rows));
  } else if(view==='clients'){
   const rows=await api('/clients');content.innerHTML=panel('Synthetic Client Directory',table([['Client',r=>esc(r.name)],['Mobile',r=>esc(r.mobile)],['Synthetic',r=>r.synthetic?'Yes':'No']],rows));
  } else if(view==='reviews'){
   const rows=await api('/reviews');content.innerHTML=panel('Human Review Queue',`<p class="note">Approving a review records an authorized decision. Only release verification changes a program to Released; completion, settlement approval and payment remain independent.</p>`+table([['Type',r=>esc(r.kind)],['Summary',r=>esc(r.summary)],['Status',r=>pill(r.status)],['Evidence',r=>evidence(r.evidence_id)],['Action',r=>r.status==='pending'?`<div class="actions"><button class="resolve" data-id="${r.id}" data-decision="approve">Approve</button><button class="resolve secondary" data-id="${r.id}" data-decision="defer">Defer</button><button class="resolve warn" data-id="${r.id}" data-decision="reject">Reject</button></div>`:'—']],rows));
   document.querySelectorAll('.resolve').forEach(b=>b.onclick=async()=>{const reason=prompt('Decision reason (synthetic demo):','Evidence reviewed');const extra={};const row=rows.find(r=>r.id===b.dataset.id);if(b.dataset.decision==='approve'&&row?.kind==='release_verification'){extra.release_date=prompt('Verified release date (YYYY-MM-DD):','')}if(b.dataset.decision==='approve'&&row?.kind==='program_completion'){extra.completion_date=prompt('Verified completion date (YYYY-MM-DD):','')}if(b.dataset.decision==='approve'&&row?.kind==='assignment_closure'){extra.previous_end_date=prompt('Evidence-supported prior assignment end date (YYYY-MM-DD):','')}if(b.dataset.decision==='approve'&&row?.kind==='assignment_replacement'){extra.previous_end_date=prompt('Evidence-supported prior assignment end date (YYYY-MM-DD):','');extra.new_escort_mobile=prompt('New Escort Mobile:','');extra.new_escort_name=prompt('New Escort Name:','');extra.new_start_date=prompt('New assignment start date (YYYY-MM-DD):','');extra.new_shift=prompt('New shift D/N:','')}if(b.dataset.decision==='approve'&&row?.kind==='program_correction'){extra.mother_vessel=prompt('Correct Mother Vessel (leave blank to skip):','')||undefined;extra.lighter_vessel=prompt('Correct Lighter Vessel (leave blank to skip):','')||undefined;extra.duty_start_date=prompt('Correct Duty Start Date (leave blank to skip):','')||undefined;extra.shift=prompt('Correct Shift D/N (leave blank to skip):','')||undefined}if(b.dataset.decision==='approve'&&row?.kind==='order_clarification_conflict'){extra.resolutions={};const details=JSON.parse(row.details);for(const conflict of details.conflicts){extra.resolutions[conflict.field]=prompt(`${conflict.field}: type existing or incoming`,'incoming')}}try{await api(`/reviews/${b.dataset.id}/resolve`,{method:'POST',body:JSON.stringify({decision:b.dataset.decision,reason,...extra})});toast('Review decision audited');render()}catch(e){toast(e.message)}});
  } else if(view==='release-slips'){
   const rows=await api('/release-slips');content.innerHTML=panel('Release Slip Evidence',`<p class="note">Uploads and manual records remain pending until an authorized reviewer verifies fields and links. Missing vessel names are allowed.</p>`+table([['Program',r=>esc(r.program_id)],['Release Date',r=>esc(r.release_date)],['Total Duty',r=>esc(r.total_duty)],['Salary Evidence',r=>esc(r.salary)],['Location',r=>esc(r.location)],['Confidence',r=>esc(r.confidence)],['Verification',r=>pill(r.verification_status)],['Source',r=>evidence(r.evidence_id)],['Original Media',r=>r.media_name?`<button class="media-link secondary" data-media="${esc(r.evidence_id)}">Open original</button>`:'—']],rows));
  } else if(view==='ghat-duty'){
   const rows=await api('/ghat-duty');content.innerHTML=panel('Ghat Duty Evidence Review',`<p class="note">BDT 200 is an indicator only. Three consecutive evidence days raise priority; attendance, salary and payment are not posted automatically.</p>`+table([['Employee Mobile',r=>esc(r.employee_id)],['Date',r=>esc(r.day)],['Amount',r=>`BDT ${esc(r.amount)}`],['Evidence Type',r=>esc(r.evidence_kind)],['Review',r=>pill(r.review_status)],['Source',r=>esc(r.evidence_id)]],rows),'<button id="new-ghat">+ Add Evidence</button>');
   document.querySelector('#new-ghat').onclick=()=>openForm('Add Ghat Duty Evidence',[field('employee_mobile','Escort Mobile',{required:true}),field('day','Evidence Date',{required:true,type:'date'}),field('amount','Amount BDT',{required:true,type:'number',value:'200'}),field('evidence_ref','Evidence reference',{required:true,value:`demo-ghat-${Date.now()}`}),field('evidence_kind','Evidence type: payment_instruction or verified_transfer',{required:true,value:'payment_instruction'})],'Create Review Candidate',d=>api('/ghat-duty',{method:'POST',body:JSON.stringify({...d,amount:Number(d.amount)})}));
  } else if(view==='settlements'){
   const rows=await api('/settlements');content.innerHTML=panel('Settlement Previews',`<p class="note">No daily rate is configured. Provide a verified/configured value explicitly; records are synthetic previews and never post to production financial services.</p>`+table([['Program',r=>esc(r.program_id)],['Days',r=>esc(r.duty_days)],['Daily Rate',r=>esc(r.daily_rate)],['Preview',r=>esc(r.preview_json)],['Status',r=>pill(r.status)],['Synthetic',r=>r.synthetic?'Yes':'No'],['Action',r=>r.status==='synthetic_preview'?`<button class="approve-settlement" data-id="${r.id}">Approve</button>`:r.status==='approved'?`<button class="paid secondary" data-id="${r.id}">Mark Synthetic Paid</button>`:'—']],rows));
   document.querySelectorAll('.approve-settlement').forEach(b=>b.onclick=async()=>{try{await api(`/settlements/${b.dataset.id}/approve`,{method:'POST',body:JSON.stringify({reason:'Synthetic demo review'})});toast('Synthetic settlement approved');render()}catch(e){toast(e.message)}});
   document.querySelectorAll('.paid').forEach(b=>b.onclick=async()=>{try{await api(`/settlements/${b.dataset.id}/mark-paid`,{method:'POST',body:JSON.stringify({synthetic_payment_reference:`demo-payment-${Date.now()}`})});toast('Synthetic payment status recorded only');render()}catch(e){toast(e.message)}});
  } else if(view==='identity'){
   const rows=await api('/identity');content.innerHTML=panel('Employee Identity',`<p class="note">Normalized Escort Mobile is the operational matching key. Internal person_uid is immutable. Same name on another mobile is separate; phone reassignment requires manual identity review.</p>`+table([['Operational employee_id (mobile)',r=>esc(r.employee_id)],['Internal person_uid',r=>esc(r.person_uid)],['Primary name',r=>esc(r.name)],['Aliases',r=>esc(r.aliases)]],rows));
  } else if(view==='audit'){
   const rows=await api('/audit');content.innerHTML=panel('Append-only Audit History',table([['Time',r=>esc(r.occurred_at)],['Entity',r=>`${esc(r.entity_type)} · ${esc(r.entity_id)}`],['Action',r=>esc(r.action)],['Actor role',r=>esc(r.actor_role)],['Evidence',r=>esc(r.evidence_id)],['Details',r=>esc(r.details)]],rows));
  } else if(view==='reports'){
   const r=await api('/reports');content.innerHTML=`<div class="alert">Synthetic-only aggregate. No historical production counts are included.</div>${panel('Program Status',table([['Status',x=>pill(x.status)],['Count',x=>esc(x.count)]],r.program_status))}${panel('Review Status',table([['Kind',x=>esc(x.kind)],['Status',x=>pill(x.status)],['Count',x=>esc(x.count)]],r.review_status))}`;
  } else if(view==='settings'){
   const r=await api('/settings');content.innerHTML=panel('Standalone Settings',`<div class="stats"><div class="card"><small>Mode</small><strong>${esc(r.mode)}</strong></div><div class="card"><small>Daily rate</small><strong>${esc(r.daily_rate)}</strong></div><div class="card"><small>Production integrations</small><strong>No</strong></div><div class="card"><small>Roles</small><strong>${r.roles.length}</strong></div></div><p class="note">Salary policy: ${esc(r.salary_policy)}. Proposed Fazle-Core, WhatsApp evidence, Cash Control and payroll adapters are documented only and disabled.</p>`);
  }
 } catch(e){content.innerHTML=`<div class="alert">API error: ${esc(e.message)}</div>`}
}
document.querySelector('#nav').addEventListener('click',e=>{if(e.target.matches('button[data-view]')){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b===e.target));view=e.target.dataset.view;render()}});
document.querySelectorAll('nav button').forEach(b=>b.dataset.icon=b.textContent.trim().slice(0,1));
document.body.addEventListener('click',async e=>{
 const evidenceButton=e.target.closest('[data-evidence]');
 if(evidenceButton){try{const item=await api(`/evidence/${encodeURIComponent(evidenceButton.dataset.evidence)}`);modalContent.innerHTML=`<h2>Source Evidence</h2><pre class="evidence-json">${esc(JSON.stringify(item,null,2))}</pre>`;modal.showModal()}catch(err){toast(err.message)}return}
 const mediaButton=e.target.closest('[data-media]');
 if(mediaButton){try{const response=await fetch(`/api/evidence/${encodeURIComponent(mediaButton.dataset.media)}/media`,{headers:{Authorization:`Bearer ${tokenSelect.value}`}});if(!response.ok)throw new Error('Media could not be loaded');const url=URL.createObjectURL(await response.blob());window.open(url,'_blank','noopener');setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(err){toast(err.message)}}
});
tokenSelect.addEventListener('change',render);
render();
